volumes:
  redis-data:
  caddy_config:
  caddy_data:

services:
  app:
    build: .
    stop_grace_period: 1s
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    expose:
      - "8080"

  redis:
    image: "redis:8-alpine"
    volumes:
      - redis-data:/data

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
